---
- name: Update pantheon
  debug:
        msg: "Updating Pantheon"

- name: Download specified pantheon source code
  git:
        repo: "https://github.com/PegaSysEng/pantheon.git"
        dest: "/tmp/pantheon"
        version: "{{ pantheon_release_commit }}"

- name: Building Pantheon
  shell: "./gradlew build -x test"
  args:
        chdir: /tmp/pantheon/

- name: Extract the Pantheon tarball
  unarchive:
        src: "/tmp/pantheon/build/distributions/pantheon-{{pantheon_current_release_number}}.tar.gz"
        dest: /usr/local
        copy: no
        
 #removing old link       
- name: Deleting old installed version of pantheon
  file:
       path: /usr/local/bin/{{ item.dest }}
       state: absent
  with_items:
        - { src: "pantheon", dest: "pantheon" }
        - { src: "pantheon.bat", dest: "pantheon.bat" }       

- name: Symbolic link for pantheon
  file:
        src: "/usr/local/pantheon-{{pantheon_current_release_number}}/bin/{{ item.src }}"
        dest: "/usr/local/bin/{{ item.dest }}"
        state: link
  with_items:
        - { src: "pantheon", dest: "pantheon" }
        - { src: "pantheon.bat", dest: "pantheon.bat" }