---
- name: Update besu
  debug:
        msg: "Updating Besu"

- name: Download specified Besu source code
  git:
        repo: "https://github.com/hyperledger/besu"
        dest: "/tmp/besu"
        version: "{{ besu_release_commit }}"

- name: Building Besu
  shell: "./gradlew build -x test"
  args:
        chdir: /tmp/besu/

- name: Getting current besu_release number
  shell: ls /tmp/besu/build/distributions/*.gz | sed 's@/tmp/besu/build/distributions/besu-@@' | sed 's/-SNAPSHOT.tar.gz//'
  register: besu_release

- debug:
    msg: "{{besu_release.stdout}}"

- name: Extract the Besu tarball  
  unarchive:
        src: "/tmp/besu/build/distributions/besu-{{besu_release.stdout}}-SNAPSHOT.tar.gz"
        dest: /usr/local
        copy: no
        
 #removing old link
- name: Deleting old installed versions of besu or pantheon
  file:
       path: /usr/local/bin/{{ item.dest }}
       state: absent
  with_items:
        - { dest: "pantheon" }
        - { dest: "pantheon.bat" }
        - { dest: "besu"}
        - { dest: "besu.bat"}

- name: Symbolic link for besu (pantheon and besu are linked to BESU)
  file:
        src: "/usr/local/besu-{{besu_release.stdout}}-SNAPSHOT/bin/{{ item.src }}"
        dest: "/usr/local/bin/{{ item.dest }}"
        state: link
  with_items:
        - { src: "besu", dest: "pantheon" }
        - { src: "besu.bat", dest: "pantheon.bat" }
        - { src: "besu", dest: "besu" }
        - { src: "besu.bat", dest: "besu.bat" }