---
- name: stop enclave #stopping node before starting the update process
  import_tasks: "stop-orion.yaml"

- name: stop pantheon #stopping node before starting the update process
  import_tasks: "stop-besu.yaml" 

- name: update orion
  import_tasks: "update-orion.yaml"

- name: init orion
  import_tasks: "init-orion.yaml"

- name: start orion
  import_tasks: "start-orion.yaml"

- name: init besu
  import_tasks: "init-besu.yaml"

- name: start besu
  import_tasks: "start-besu.yaml"